apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: character-battle
resources:
  - namespace.yaml
  - app-configmap.yaml
  - app-secret.example.yaml
  - postgres-init-configmap.yaml
  - postgres.yaml
  - redis.yaml
  - backend.yaml
  - frontend.yaml

